#include "engine.h"
#include "js_engine.h"
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int low(int c){return tolower((unsigned char)c);}
static bool eqci(const char*a,const char*b){if(!a||!b)return false;while(*a&&*b){if(low(*a)!=low(*b))return false;a++;b++;}return *a==0&&*b==0;}
static bool swci(const char*s,const char*p){if(!s||!p)return false;while(*p){if(!*s||low(*s)!=low(*p))return false;s++;p++;}return true;}
static const char* fci(const char*h,const char*n){if(!h||!n||!*n)return NULL;size_t l=strlen(n);for(const char*p=h;*p;p++){size_t i=0;while(i<l&&p[i]&&low(p[i])==low(n[i]))i++;if(i==l)return p;}return NULL;}
static void tc(char*d,size_t ds,const char*s,size_t n){while(n&&isspace((unsigned char)*s)){s++;n--;}while(n&&isspace((unsigned char)s[n-1]))n--;if(n>=ds)n=ds-1;memcpy(d,s,n);d[n]=0;}
static void add_err(EngineDoc*d,const char*m){if(d&&m&&d->error_count<ENG_MAX_ERRS)snprintf(d->errors[d->error_count++],160,"%s",m);}
static int add_node(EngineDoc*d,NodeType t,int par,const char*tag){if(d->node_count>=ENG_MAX_NODES){add_err(d,"DOM node limit reached.");return-1;}int i=d->node_count++;Node*n=&d->nodes[i];memset(n,0,sizeof(*n));n->type=t;n->parent=par;n->first_child=-1;n->next_sibling=-1;if(tag)snprintf(n->tag,24,"%s",tag);if(par>=0&&par<d->node_count){Node*p=&d->nodes[par];if(p->first_child<0)p->first_child=i;else{int c=p->first_child;while(c>=0&&d->nodes[c].next_sibling>=0)c=d->nodes[c].next_sibling;if(c>=0)d->nodes[c].next_sibling=i;}}return i;}
static void app_text(EngineDoc*d,const char*s){size_t u=strlen(d->render_text),r=PREVIEW_TEXT_MAX-u-1;if(r)strncat(d->render_text,s,r);}
static void appc(EngineDoc*d,char c){char s[2]={c,0};app_text(d,s);}
static void nl(EngineDoc*d){size_t n=strlen(d->render_text);if(n&&d->render_text[n-1]!='\n')appc(d,'\n');}
static bool block(const char*t){return eqci(t,"html")||eqci(t,"body")||eqci(t,"div")||eqci(t,"p")||eqci(t,"h1")||eqci(t,"h2")||eqci(t,"h3")||eqci(t,"ul")||eqci(t,"ol")||eqci(t,"li")||eqci(t,"section")||eqci(t,"article")||eqci(t,"main");}
static void tagname(const char*t,char*out,size_t os,bool*cl,bool*sc){out[0]=0;*cl=false;*sc=false;const char*p=t;while(*p&&isspace((unsigned char)*p))p++;if(*p=='/'){*cl=true;p++;}while(*p&&isspace((unsigned char)*p))p++;size_t i=0;while(*p&&(isalnum((unsigned char)*p)||*p=='-'||*p=='_')&&i+1<os)out[i++]=(char)low(*p++);out[i]=0;if(eqci(out,"br")||eqci(out,"img")||eqci(out,"meta")||eqci(out,"link")||eqci(out,"input")||eqci(out,"hr"))*sc=true;}
static void text_node(EngineDoc*d,int par,const char*s,size_t l){char tmp[192];tc(tmp,sizeof(tmp),s,l);if(!tmp[0])return;int i=add_node(d,NODE_TEXT,par,NULL);if(i>=0)snprintf(d->nodes[i].text,192,"%s",tmp);app_text(d,tmp);appc(d,' ');}
static void title(EngineDoc*d,const char*h){const char*a=fci(h,"<title");if(!a)return;const char*g=strchr(a,'>');if(!g)return;const char*b=fci(g+1,"</title>");if(!b)return;tc(d->title,128,g+1,(size_t)(b-g-1));}
static void css_rule(EngineDoc*d,const char*ss,const char*bs,size_t bl){if(d->css_count>=ENG_MAX_CSS)return;const char*br=strchr(ss,'{');if(!br)return;CssRule*r=&d->css[d->css_count];memset(r,0,sizeof(*r));tc(r->selector,48,ss,(size_t)(br-ss));char body[512];if(bl>=sizeof(body))bl=sizeof(body)-1;memcpy(body,bs,bl);body[bl]=0;char*p=body;while(*p){while(*p&&(isspace((unsigned char)*p)||*p==';'))p++;char*c=strchr(p,':');if(!c)break;*c=0;char*v=c+1;char*semi=strchr(v,';');if(semi)*semi=0;char prop[64],val[64];tc(prop,64,p,strlen(p));tc(val,64,v,strlen(v));if(eqci(prop,"color"))snprintf(r->color,32,"%s",val);else if(eqci(prop,"background")||eqci(prop,"background-color"))snprintf(r->background,32,"%s",val);else if(eqci(prop,"font-size"))r->font_size=atoi(val);if(!semi)break;p=semi+1;}if(r->selector[0])d->css_count++;}
static void css_block(EngineDoc*d,const char*s,size_t l){const char*p=s,*e=s+l;while(p<e){const char*o=memchr(p,'{',(size_t)(e-p));if(!o)break;const char*c=memchr(o+1,'}',(size_t)(e-o-1));if(!c){add_err(d,"Unclosed CSS rule.");break;}css_rule(d,p,o+1,(size_t)(c-o-1));p=c+1;}}
static const CssRule* rule_for(EngineDoc*d,const char*t){for(int i=0;i<d->css_count;i++)if(eqci(d->css[i].selector,t))return &d->css[i];return NULL;}
static int add_box(EngineDoc*d,BoxType t,int ni,int x,int y,int w,int h){if(d->box_count>=ENG_MAX_BOXES)return-1;int i=d->box_count++;LayoutBox*b=&d->boxes[i];memset(b,0,sizeof(*b));b->type=t;b->node_index=ni;b->x=x;b->y=y;b->w=w;b->h=h;snprintf(b->color,32,"white");snprintf(b->background,32,"black");if(t==BOX_BLOCK)d->block_box_count++;else if(t==BOX_TEXT)d->text_box_count++;else if(t==BOX_IMAGE)d->image_box_count++;return i;}
static int lh(const char*t){return eqci(t,"h1")?22:eqci(t,"h2")?18:eqci(t,"h3")?16:12;}
static void layout(EngineDoc*d,int ni,int dep,int*y){if(ni<0||ni>=d->node_count)return;Node*n=&d->nodes[ni];if(n->type==NODE_COMMENT)return;if(n->type==NODE_TEXT){int x=12+dep*6;BoxType bt=strstr(n->text,"[image]")?BOX_IMAGE:BOX_TEXT;int bi=add_box(d,bt,ni,x,*y,bt==BOX_IMAGE?80:TOP_W-x-12,bt==BOX_IMAGE?48:12);if(bi>=0){snprintf(d->boxes[bi].tag,24,bt==BOX_IMAGE?"img":"#text");snprintf(d->boxes[bi].text,96,"%s",n->text);}*y+=bt==BOX_IMAGE?54:14;if(*y>d->content_height)d->content_height=*y;return;}bool ib=n->type==NODE_DOCUMENT||block(n->tag);int x=dep==0?0:8+dep*4,sy=*y;int bi=add_box(d,ib?BOX_BLOCK:BOX_INLINE,ni,x,sy,TOP_W-x-8,lh(n->tag));if(bi>=0){snprintf(d->boxes[bi].tag,24,"%s",n->tag[0]?n->tag:"#document");const CssRule*r=rule_for(d,n->tag);if(r){if(r->color[0])snprintf(d->boxes[bi].color,32,"%s",r->color);if(r->background[0])snprintf(d->boxes[bi].background,32,"%s",r->background);}}if(ib&&n->type!=NODE_DOCUMENT)*y+=4;for(int c=n->first_child;c>=0;c=d->nodes[c].next_sibling)layout(d,c,dep+1,y);if(ib&&n->type!=NODE_DOCUMENT)*y+=4;if(bi>=0&&*y-sy>d->boxes[bi].h)d->boxes[bi].h=*y-sy;if(*y>d->content_height)d->content_height=*y;}
void engine_parse_and_layout(const char*h,EngineDoc*d){memset(d,0,sizeof(*d));add_node(d,NODE_DOCUMENT,-1,"#document");if(!h||!*h){add_err(d,"Empty document.");snprintf(d->title,128,"Untitled");return;}title(d,h);resource_scan_html(h,&d->resources);int st[64],sp=0;st[0]=0;bool hh=false,hb=false;const char*p=h;while(*p){if(swci(p,"<!--")){const char*e=strstr(p+4,"-->");if(!e){add_err(d,"Unclosed HTML comment.");break;}add_node(d,NODE_COMMENT,st[sp],NULL);p=e+3;continue;}if(*p!='<'){const char*n=strchr(p,'<');if(!n)n=p+strlen(p);text_node(d,st[sp],p,(size_t)(n-p));p=n;continue;}const char*g=strchr(p,'>');if(!g){add_err(d,"Unclosed tag.");break;}char tt[512];size_t tl=(size_t)(g-p-1);if(tl>=sizeof(tt))tl=sizeof(tt)-1;memcpy(tt,p+1,tl);tt[tl]=0;char tg[24];bool cl=false,sc=false;tagname(tt,tg,24,&cl,&sc);if(!tg[0]||tg[0]=='!'){p=g+1;continue;}if(cl){if(sp>0){int m=-1;for(int i=sp;i>0;i--)if(eqci(d->nodes[st[i]].tag,tg)){m=i;break;}if(m>=0)sp=m-1;else add_err(d,"Closing tag without matching open.");}if(block(tg))nl(d);p=g+1;continue;}if(eqci(tg,"html"))hh=true;if(eqci(tg,"body"))hb=true;int idx=add_node(d,NODE_ELEMENT,st[sp],tg);if(block(tg))nl(d);if(eqci(tg,"img"))text_node(d,st[sp],"[image]",7);if(eqci(tg,"style")){d->style_count++;const char*e=fci(g+1,"</style>");if(e){css_block(d,g+1,(size_t)(e-g-1));p=e+8;continue;}else add_err(d,"Unclosed <style> block.");}if(eqci(tg,"script")){d->script_count++;const char*e=fci(g+1,"</script>");if(e){p=e+9;continue;}else add_err(d,"Unclosed <script> block.");}if(!sc&&idx>=0&&sp+1<64)st[++sp]=idx;p=g+1;}if(!hh)add_err(d,"Missing <html> element.");if(!hb)add_err(d,"Missing <body> element.");if(!d->title[0])snprintf(d->title,128,"Untitled");js_execute_inline_scripts(h,d);int y=0;layout(d,0,0,&y);resource_fetch_manifest(&d->resources,RES_MAX_BYTES);}
HtmlCheck engine_check(const char*h){EngineDoc d;engine_parse_and_layout(h,&d);HtmlCheck c;c.errors=d.error_count;c.message[0]=0;if(!c.errors){snprintf(c.message,512,"OK");return c;}for(int i=0;i<d.error_count;i++){size_t u=strlen(c.message);if(u+4>=sizeof(c.message))break;snprintf(c.message+u,sizeof(c.message)-u,"%s%s",u?" ":"",d.errors[i]);}return c;}
