#include "resource_loader.h"
#include "fs_io.h"
#include "net_fetch.h"
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int low(int c){return tolower((unsigned char)c);}
static bool swci(const char*s,const char*p){while(*p){if(!*s||low(*s)!=low(*p))return false;s++;p++;}return true;}
static const char*fci(const char*h,const char*n){if(!h||!n||!*n)return NULL;size_t l=strlen(n);for(const char*p=h;*p;p++){size_t i=0;while(i<l&&p[i]&&low(p[i])==low(n[i]))i++;if(i==l)return p;}return NULL;}
static bool contains(const char*h,const char*n){return fci(h,n)!=NULL;}
static unsigned long hash_url(const char*s){unsigned long h=5381;int c;while((c=*s++))h=((h<<5)+h)+(unsigned char)c;return h;}
static const char* ext(ResourceType t){return t==RES_CSS?".css":t==RES_JS?".js":t==RES_IMAGE?".bin":".dat";}
void resource_manifest_init(ResourceManifest*m){if(m)memset(m,0,sizeof(*m));}
static bool exists(const ResourceManifest*m,const char*u){for(int i=0;m&&i<m->count;i++)if(strcmp(m->items[i].url,u)==0)return true;return false;}
static void cpath(ResourceItem*it){snprintf(it->cache_path,sizeof(it->cache_path),"%s/%08lx%s",APP_CACHE_DIR,hash_url(it->url),ext(it->type));}
static void add(ResourceManifest*m,ResourceType t,const char*u){if(!m||!u||!*u)return;if(!(swci(u,"http://")||swci(u,"https://")))return;if(exists(m,u))return;if(m->count>=RES_MAX_ITEMS){m->truncated_count++;return;}ResourceItem*it=&m->items[m->count++];memset(it,0,sizeof(*it));it->type=t;it->status=RES_PENDING;snprintf(it->url,sizeof(it->url),"%s",u);snprintf(it->status_text,sizeof(it->status_text),"pending");cpath(it);if(t==RES_CSS)m->css_count++;else if(t==RES_JS)m->js_count++;else if(t==RES_IMAGE)m->image_count++;else m->other_count++;}
static void attr(const char*tag,const char*a,char*out,size_t os){out[0]=0;const char*p=fci(tag,a);if(!p)return;p+=strlen(a);while(*p&&isspace((unsigned char)*p))p++;if(*p!='=')return;p++;while(*p&&isspace((unsigned char)*p))p++;char q=0;if(*p=='"'||*p=='\''){q=*p;p++;}size_t i=0;while(*p&&i+1<os){if(q){if(*p==q)break;}else if(isspace((unsigned char)*p)||*p=='>')break;out[i++]=*p++;}out[i]=0;}
static void scan_tags(const char*h,ResourceManifest*m){const char*p=h;while((p=strchr(p,'<'))){const char*g=strchr(p,'>');if(!g)break;char tag[768];size_t l=(size_t)(g-p+1);if(l>=sizeof(tag))l=sizeof(tag)-1;memcpy(tag,p,l);tag[l]=0;char u[URL_MAX];if(contains(tag,"<link")&&contains(tag,"stylesheet")){attr(tag,"href",u,sizeof(u));add(m,RES_CSS,u);}else if(contains(tag,"<script")){attr(tag,"src",u,sizeof(u));add(m,RES_JS,u);}else if(contains(tag,"<img")){attr(tag,"src",u,sizeof(u));add(m,RES_IMAGE,u);}p=g+1;}}
static void scan_urls(const char*h,ResourceManifest*m){const char*c=h;while(c&&*c){const char*a=fci(c,"http://"),*b=fci(c,"https://");const char*n=a&&b?(a<b?a:b):(a?a:b);if(!n)break;char tmp[URL_MAX];size_t i=0;while(n[i]&&n[i]!='"'&&n[i]!='\''&&n[i]!='<'&&n[i]!='>'&&!isspace((unsigned char)n[i])&&i+1<sizeof(tmp)){tmp[i]=n[i];i++;}tmp[i]=0;add(m,RES_OTHER,tmp);c=n+7;}}
void resource_scan_html(const char*h,ResourceManifest*m){resource_manifest_init(m);if(!h||!m)return;scan_tags(h,m);scan_urls(h,m);}
void resource_fetch_manifest(ResourceManifest*m,size_t max){if(!m)return;if(!max)max=RES_MAX_BYTES;if(max>RES_MAX_BYTES)max=RES_MAX_BYTES;if(!fs_make_cache_dir()){for(int i=0;i<m->count;i++){m->items[i].status=RES_FAILED;snprintf(m->items[i].status_text,sizeof(m->items[i].status_text),"cache dir failed");m->failed_count++;}return;}char*buf=(char*)malloc(max+1);if(!buf){for(int i=0;i<m->count;i++){m->items[i].status=RES_FAILED;snprintf(m->items[i].status_text,sizeof(m->items[i].status_text),"alloc failed");m->failed_count++;}return;}for(int i=0;i<m->count;i++){ResourceItem*it=&m->items[i];char err[128];size_t got=0;bool ok=net_fetch_url_limit_ex(it->url,buf,max+1,max,&got,err,sizeof(err));if(!ok){if(strstr(err,"1 MB")||strstr(err,"exceeds")){it->status=RES_TOO_LARGE;snprintf(it->status_text,sizeof(it->status_text),"too large");m->too_large_count++;}else{it->status=RES_FAILED;snprintf(it->status_text,sizeof(it->status_text),"%.90s",err);m->failed_count++;}continue;}it->size_bytes=got;if(it->type==RES_IMAGE){image_decode_metadata((const unsigned char*)buf,it->size_bytes,&it->image_info);}if(fs_save_bytes(it->cache_path,buf,it->size_bytes)){it->status=RES_CACHED;if(it->type==RES_IMAGE&&it->image_info.decoded_metadata)snprintf(it->status_text,sizeof(it->status_text),"cached %s %dx%d",image_kind_name(it->image_info.kind),it->image_info.width,it->image_info.height);else snprintf(it->status_text,sizeof(it->status_text),"cached %lu bytes",(unsigned long)it->size_bytes);m->cached_count++;}else{it->status=RES_FAILED;snprintf(it->status_text,sizeof(it->status_text),"cache write failed");m->failed_count++;}}free(buf);}
